name: hyeconomy
version: '${version}'
main: xyz.hynse.hyeconomy.Hyeconomy
api-version: '1.20'
folia-supported: true
description: economy using diamonds. Manage your SMP!
author: [MidnightTale_, MDCason]
website: https://hynse.xyz
commands:
  balance:
    description: Check your balance
    usage: /balance
    aliases: [bal]
    permission: hyeconomy.balance
  deposit:
    description: Deposit diamonds into your account
    usage: /dp <amount>
    aliases: [dp]
    permission: hyeconomy.deposit
  send:
    description: Send diamonds to another player
    usage: /dsend <player> <amount>
    aliases: [dsend]
    permission: hyeconomy.send
  top:
    description: Display the leaderboard of players with the most diamonds
    usage: /dtop [count]
    aliases: [dtop]
    permission: hyeconomy.top
  withdraw:
    description: Withdraw diamonds from your account
    usage: /wd <amount>
    aliases: [wd]
    permission: hyeconomy.withdraw
  hyeconomyreload:
    description: Reload Config and Messages
    usage: /dreload
    permission: hyeconomy.reload
    aliases: [dreload]
    default: op
libraries:
  - com.zaxxer:HikariCP:5.0.1
  - org.mariadb.jdbc:mariadb-java-client:3.2.0
  - net.kyori:adventure-text-minimessage:4.14.0