name: hyeconomy
version: '${version}'
main: xyz.hynse.hyeconomy.Hyeconomy
api-version: '1.20'
folia-supported: true
description: Basic economy plugin for Minecraft using diamonds.
author: MidnightTale_